openapi: 3.0.1
info:
  title: Wordpress
  description: Wordpres Test Site
  x-cortex-owners:
   -
    email: jselleck@sans.org
    type: EMAIL
  x-cortex-tag: wordpress
  x-cortex-git:
    github:
      repository: sans-software/wordpress
